entando/entando-docs

docs/src/main/asciidoc/custom-app-building/custom-app-building.adoc, docs/src/main/asciidoc/getting-started/getting-started.adoc, docs/src/main/asciidoc/installation/installation.adoc
Fixed underscores in examples/tutorials for the Code field in Appbuilder, and removes some warnings in documentation build.
=> Fix tutorials

docs/src/main/asciidoc/CMS/cms.adoc, docs/src/main/asciidoc/asciidoctor.css, docs/src/main/asciidoc/digital-exchange/digital-exchange.adoc, docs/src/main/asciidoc/index.adoc, docs/src/main/asciidoc/index.html
I also fixed issues on CMS docs. That section was not included and the `anchor:` in the titles caused menu rendering issues, so I removed them.
=> Added Digital Exchange docs & CMS fix

docs/src/main/asciidoc/cloud-deployments/kubernetes.adoc, docs/src/main/asciidoc/index.adoc, docs/src/main/asciidoc/index.html
Add a section `cloud-deployments` to show how to deploy a simple entando project on a kubernetes cluster
=> Cloud envs

vuepress/docs/.vuepress/config.js, vuepress/docs/ecr/ecr-troubleshooting-guide.md
This is going to be a living document, I've started with some of the most common issues
=> Eng 348 ecr troubleshooting guide

vuepress/docs/docs/reference/cluster-resource-limits.md
I've added some doc about ECR bundle size limitations
=> ENG-559 bundle size limitations docs

vuepress/docs/next/docs/concepts/README.md, vuepress/docs/next/tutorials/ecr/ecr-how-microservices-connects-to-apps.md
I tweaked the links to use the auto-generated anchors and also so the check-md link checker will be satisfied. This ends up being a little less code too.
=> ENG-982 Use standard vuepress anchors to satisfy check-md.

vuepress/docs/.vuepress/components/SpecialLayout.vue
Could also go with "developers" or "engineers". Landed on "users". For sure "team" doesn't seem right.
=> reword openshift intro to users

vuepress/.gitignore, vuepress/docs/next/tutorials/devops/installation/google-cloud-platform/README.md
Update the references for 6.3 and fix the formatting on commands to match other tutorials.
=> Update gke tutorial for 6.3

vuepress/docs/.vuepress/components/SpecialLayout.vue, vuepress/docs/next/docs/getting-started/README.md, vuepress/docs/next/docs/reference/entando-cli.md, vuepress/docs/v6.3/docs/getting-started/README.md, vuepress/docs/v6.3/docs/reference/entando-cli.md
This reverts commit 70c35dd3201aa8ef84c8150b7404f4708b3df81a, reversing
changes made to c605a716f0d0ef5c1b6d0ffeb36868b7894893f7.
=> Revert "Merge pull request #275 from entando/tmp-link-update"

vuepress/package.json, vuepress/yarn.lock
Tested locally and in staging.
=> Update vuepress, ssri, and is-svg per dependabot warnings.

vuepress/docs/.vuepress/next.js, vuepress/docs/.vuepress/v63.js, vuepress/docs/next/docs/concepts/operator-intro.md, vuepress/docs/v6.3/docs/concepts/operator-intro.md
This should be viewed in concert with:
https://github.com/entando-k8s/entando-k8s-operator-bundle/pull/8
Which links to these docs.
=> ENDOC-311 update crd descriptions and migrate details to docs

vuepress/docs/.vuepress/components/EntandoVersionLinks.vue, vuepress/docs/.vuepress/next.js, vuepress/docs/.vuepress/v632.js, vuepress/docs/next/docs/concepts/accessibility.md, vuepress/docs/v6.3.2/docs/concepts/accessibility.md, vuepress/package.json, vuepress/yarn.lock
A couple fixes here but the main one is the accessibility content. Visible on the staging site now: https://entando.github.io/entando-docs/v6.3.2/docs/concepts/accessibility.html#requirements-and-standards
=> Endoc 340 accessibility

vuepress/docs/next/tutorials/devops/installation/elastic-kubernetes-service/eks-install.md
- Add note about IAM Role
- Move the create namespace
- Apply the operator config
=> missing steps for EKS install

vuepress/docs/next/tutorials/devops/installation/google-cloud-platform/gke-install.md, vuepress/docs/v6.3.2/tutorials/devops/installation/google-cloud-platform/gke-install.md
This had to be rewritten to match the latest GKE but now it successfully installs
=> ENDOC-357 Update the GKE install instructions

vuepress/docs/next/docs/concepts/custom-resources.md, vuepress/docs/v6.3.2/docs/concepts/custom-resources.md
Edited custom-resources.md on 10/20/2021. This is a test.
=> Custom resource edit

vuepress/docs/v6.3.2/docs/releases/README.md
Add issue to the 6.3.2 release notes to document the change to database vs databaseName
=> ENDOC-360 custom resource change in release notes

vuepress/README.md, vuepress/docs/next/docs/concepts/custom-resources.md, vuepress/docs/v6.3.2/docs/concepts/custom-resources.md
Fixed links in v6.3.2 custom-resources.md, next custom-resources.md and added text to Readme.md for Versions. I am unsure about the txt in the readme.
=> Endoc-367 Fix links in Custom Resources

vuepress/docs/next/tutorials/devops/installation/open-shift/openshift-install-by-operator-hub.md, vuepress/docs/next/tutorials/devops/installation/open-shift/openshift-install.md
Added SSL Certificate Error under Troubleshooting. First Draft. 
Don't think change is needed for Left-nav menu but need to check.
=> ENDOC-356 add issue note re:docker io

vuepress/docs/next/docs/getting-started/README.md, vuepress/docs/v6.3.2/docs/getting-started/README.md
Merge with other changes submitted
=> ENDOC-377 Timeout settings

vuepress/docs/next/tutorials/devops/installation/azure-kubernetes-service/azure-install.md, vuepress/docs/next/tutorials/devops/installation/elastic-kubernetes-service/eks-install.md, vuepress/docs/next/tutorials/devops/installation/google-cloud-platform/gke-install.md, vuepress/docs/v6.3.2/tutorials/devops/installation/azure-kubernetes-service/azure-install.md, vuepress/docs/v6.3.2/tutorials/devops/installation/elastic-kubernetes-service/eks-install.md, vuepress/docs/v6.3.2/tutorials/devops/installation/google-cloud-platform/gke-install.md
=> ENDOC-386 Add a tip about customizing the nginx ingress configuration

vuepress/docs/next/tutorials/samples/install-standard-demo.md
first pass... i need to get localhost up and running on my new machine to view formatting
=> ENDOC-390 Update the Standard Banking Demo page to match current style guidelines

vuepress/docs/v6.3.2/docs/releases/README.md
Add a release note re docker hub numeric account names breaking deployment of plugins
=> ENDOC-391 Added note to Known Issues

vuepress/docs/next/docs/reference/entando-cli.md
ENDOC-394 Add a tutorial on how to use ent profile to connect to k8s and change environments
=> ENDOC-394 First pass at `ent profile` updates

vuepress/docs/next/tutorials/devops/installation/azure-kubernetes-service/azure-install.md, vuepress/docs/next/tutorials/devops/installation/google-cloud-platform/gke-install.md, vuepress/docs/v6.3.2/tutorials/devops/installation/azure-kubernetes-service/azure-install.md, vuepress/docs/v6.3.2/tutorials/devops/installation/google-cloud-platform/gke-install.md
Note on configuring storage class. Are the format and location of this comment appropriate?
=> ENDOC-405 Add instructions to configure a different storage class to Azure doc

vuepress/docs/next/tutorials/create/ms/generate-microservices-and-micro-frontends.md, vuepress/docs/next/tutorials/create/ms/update-data-model.md
Update "generate ms and mfes" (file 1 of 2)
=> ENDOC-362 update the documentation with the finding resulting from the jhipster 7.2 upgrade spike

vuepress/docs/next/docs/getting-started/README.md, vuepress/docs/next/docs/reference/entando-cli.md
URLs need to change to final addresses
=> ENDOC-460 Update the manual quickstart install guide for 7.0

vuepress/docs/next/docs/consume/identity-management.md, vuepress/docs/next/tutorials/solution/customer-portal.md, vuepress/docs/next/tutorials/solution/entando-hub.md, vuepress/docs/next/tutorials/solution/install-standard-demo.md, vuepress/docs/next/tutorials/solution/pda-tutorial.md, vuepress/docs/v6.3.2/tutorials/solution/entando-hub.md
will add to v6.3.2 once edits are done
=> ENDOC-477 Add client role instructions

vuepress/docs/next/docs/compose/ecr-overview.md, vuepress/docs/next/docs/reference/databases.md
This was merged into v7.0 last week but forgot to do it for next. This applies the exact same edits.
=> ENDOC-496 apply update to next for ecr-overview.md & databases.md

vuepress/docs/next/tutorials/getting-started/gke-install.md, vuepress/docs/v7.0/tutorials/getting-started/gke-install.md
Just had a call with a partner about this and we though that this case needs a bit of highlighting
=> Add tip for private cluster installation on GKE

vuepress/docs/.vuepress/v70.js, vuepress/docs/next/docs/consume/custom-resources.md, vuepress/docs/next/docs/consume/database-cr.md, vuepress/docs/next/docs/consume/entandoapp-cr.md, vuepress/docs/next/docs/consume/keycloak-cr.md, vuepress/docs/next/tutorials/getting-started/azure-install.md, vuepress/docs/next/tutorials/getting-started/eks-install.md, vuepress/docs/next/tutorials/getting-started/gke-install.md, vuepress/docs/next/tutorials/getting-started/openshift-install.md, vuepress/docs/v7.0/docs/consume/custom-resources.md, vuepress/docs/v7.0/docs/consume/database-cr.md, vuepress/docs/v7.0/docs/consume/entandoapp-cr.md, vuepress/docs/v7.0/docs/consume/keycloak-cr.md, vuepress/docs/v7.0/tutorials/getting-started/azure-install.md, vuepress/docs/v7.0/tutorials/getting-started/eks-install.md, vuepress/docs/v7.0/tutorials/getting-started/gke-install.md, vuepress/docs/v7.0/tutorials/getting-started/openshift-install.md
Added the new CR pages in Left Nav. Not sure if they belong there but wanted to see how it would feel. The links to the specific new CR pages are also available at the intro section of the main CR page. Let me know what you think. 
the broken link is in a comment and it is for the EntandoDeBundle that is still under construction. I'll take the comment out as needed.
=> ENDOC-493 Update CRs

vuepress/docs/.vuepress/components/EntandoCode.vue, vuepress/docs/.vuepress/config.js, vuepress/docs/next/docs/getting-started/README.md, vuepress/docs/next/tutorials/getting-started/azure-install.md, vuepress/docs/next/tutorials/getting-started/eks-install.md, vuepress/docs/next/tutorials/getting-started/gke-install.md
Major change is to move the fixpack version (v7.1.0) into the config.js so we can update the fixpack version in one place rather than modifying 5 files and 4 lines in each.
=> ENDOC-557 update azure install

vuepress/docs/next/tutorials/create/mfe/react.md
Link to publish project tutorial
=> ENDOC-561 Publish a simple MFE

vuepress/docs/next/docs/compose/local-hub-overview.md
=> Fix typo error in local-hub-overview.md

vuepress/docs/next/docs/getting-started/ent-bundle.md, vuepress/docs/next/tutorials/create/ms/update-data-model.md
getting concepts/language in place pending finalized jhipster tutorial
=> ENDOC-547 7.1 Update v1 and Create new v5: Update the Prj Data Model tutorial

vuepress/docs/next/docs/create/blueprint-features.md, vuepress/docs/next/docs/curate/bundle-component-details.md, vuepress/docs/next/tutorials/create/ms/generate-microservices-and-micro-frontends.md
these are the same approved updates on v7.1 applied to next
=> ENDOC-579B copy updates to next

vuepress/docs/next/docs/compose/local-hub-overview.md, vuepress/docs/v7.1/docs/compose/local-hub-overview.md
broken links are expected; references are not yet in place
=> ENDOC-621 update local hub overview

vuepress/docs/.vuepress/next.js, vuepress/docs/next/tutorials/create/ms/spring-boot-ms.md
@Lyd1aCla1r3, can you test the tutorial too.
=> ENDOC-611 add spring boot MS

vuepress/docs/next/tutorials/devops/manage-nginx.md, vuepress/docs/v7.1/tutorials/devops/manage-nginx.md
...don't ask. files got messed up but should all be ok now
=> ENDOC-642b Add annotation to Manage NGINX tutorial

vuepress/docs/v7.1/tutorials/solution/customer-portal.md
=> ENDOC-647b 

vuepress/docs/v6.3.2/docs/compose/ecr-overview.md
Reverts entando/entando-docs#681
=> Revert "test ecr-overview.md"

vuepress/README.md, vuepress/docs/.vuepress/styles/index.styl, vuepress/docs/.vuepress/vuepress-pdf.config.ts, vuepress/package.json
Same export can be found here - https://drive.google.com/drive/folders/1EnfFo_DKZf9Yyr53Hn6e6ij16p2GfK0Y?usp=share_link
=> ENDOC-664 add feature to export site as PDF

vuepress/docs/next/docs/create/blueprint-features.md, vuepress/docs/v7.1/docs/create/blueprint-features.md
this is the PR (ENDOC-667) already reviewed by @nshaw and @jyunmitch, because the original got corrupted with a merge
=> ENDOC-667-blueprint doc update

vuepress/docs/next/docs/curate/bundle-details.md, vuepress/docs/v7.2/docs/curate/bundle-details.md
This is a short update but the Eng tickets were rather hard to pull together so I'm asking all of your review. This is to document the healthCheckIngress and ingressPath for the miscroservices. 
The recommendation for the API claim in the v1 to v5 conversion is included in another ticket.
=> ENDOC-729-MS-resource

vuepress/docs/next/docs/curate/bundle-component-details.md, vuepress/docs/v7.3/docs/curate/bundle-component-details.md
@nicpuddu @eugeniosant should this be noted on earlier versions, like entando v7.2, v7.1, etc? 
BTW, I reordered the page to be alphabetical so you can ignore all the changes except for the last two paragraphs for `Contents`.
=> ENDOC-761-content-links

vuepress/docs/v7.3/docs/releases/README.md
Please add reviewers if there are additional people who should check this document.
Also note that some points have been repeated under different headings. That was intentional, in case people just scan certain sections. It's also to highlight some things. Of course, if points don't belong under that heading, leave a comment.
THANK YOU!
=> ENDOC-748-730Release

vuepress/docs/next/docs/consume/multitenancy.md, vuepress/docs/next/docs/curate/bundle-details.md, vuepress/docs/next/tutorials/consume/multitenancy.md, vuepress/docs/v7.3/docs/consume/multitenancy.md, vuepress/docs/v7.3/docs/curate/bundle-details.md, vuepress/docs/v7.3/tutorials/consume/multitenancy.md
the failed checks are related to the new External DBMS for MT microservices tutorial which is coming next.
=> ENDOC-766-MT-bundle-install general

vuepress/docs/next/tutorials/consume/external-db-ms.md, vuepress/docs/v7.3/docs/curate/bundle-component-details.md, vuepress/docs/v7.3/docs/getting-started/ent-bundle.md, vuepress/docs/v7.3/docs/reference/bundle-comparison.md, vuepress/docs/v7.3/tutorials/compose/role-users-groups.md, vuepress/docs/v7.3/tutorials/consume/external-db-ms.md, vuepress/docs/v7.3/tutorials/create/ms/add-access-controls.md, vuepress/docs/v7.3/tutorials/create/ms/spring-boot-ms.md, vuepress/docs/v7.3/tutorials/solution/install-standard-demo.md
@jyunmitch I ran a yarn docs:syncNext so you'll want to confirm that next was actually the correct code. It wasn't obvious to me if next was completely the source of truth right now so apologies there.
=> Endoc 776 syntax

vuepress/docs/next/docs/reference/database-cr.md, vuepress/docs/next/docs/reference/keycloak-cr.md, vuepress/docs/next/tutorials/devops/external-db.md, vuepress/docs/v7.3/docs/reference/database-cr.md, vuepress/docs/v7.3/docs/reference/keycloak-cr.md, vuepress/docs/v7.3/tutorials/devops/external-db.md
This was previously in a another PR which you approved but after discussion with @pietrangelo, the configuration for Oracle DBMS was moved to the external DB page.
=> ENDOC-753-ext-oracle

vuepress/docs/next/docs/consume/identity-management.md, vuepress/docs/next/tutorials/curate/private-git-repo.md, vuepress/docs/v7.0/tutorials/curate/ecr-private-images.md, vuepress/docs/v7.2/docs/consume/identity-management.md, vuepress/docs/v7.3/docs/consume/identity-management.md, vuepress/docs/v7.3/tutorials/curate/private-git-repo.md
@antoalv19 note the old links to keycloak 18 had to be updated to Keycloak 21, which is the oldest available. But our compatibility for Keycloak is 18. Hope this is ok
=> ENDOC-819 link fixes & misc
