docs/src/main/asciidoc/entando-6.1.0/blueprint/create-plugin-blueprint.adoc
Hi @joewhite101 @Kerruba @gidesan ,
added in the blueprint guide the new steps to run the generated widgets ([related to this PR](https://github.com/entando/entando-blueprint/pull/54)).
Could you please have a look?
Thanks.
@joewhite101 I added a folder as example at point 4 of the "Setup for Blueprint Dev mode" section, because I use that as example in the rest of the guide (only in the new steps added in this PR)
=> ENG-404: added new steps to run the generated widgets

vuepress/docs/next/docs/reference/entando-apis.md, vuepress/docs/next/tutorials/customize-the-platform/app-engine/build-core-image.md, vuepress/docs/next/tutorials/customize-the-platform/app-engine/building-prepackaged-image.md, vuepress/docs/next/tutorials/customize-the-platform/app-engine/core-swagger.md, vuepress/docs/next/tutorials/devops/build-core-image.md, vuepress/docs/v6.1/docs/reference/core-swagger.md, vuepress/docs/v6.1/docs/reference/entando-apis.md, vuepress/docs/v6.1/tutorials/customize-the-platform/app-engine/build-core-image.md, vuepress/docs/v6.1/tutorials/customize-the-platform/app-engine/building-prepackaged-image.md, vuepress/docs/v6.1/tutorials/customize-the-platform/app-engine/core-swagger.md, vuepress/docs/v6.1/tutorials/devops/build-core-image.md
Updated the refs in 6.1 as well since the entando-sample-app would be equally broken there.
=> ENDOC-58 remove sample app refs

vuepress/docs/next/tutorials/ecr/ecr-bundle-details.md
Adds the `defaultWidget` field to  the page-template descriptor as now is supported in the API
=> ENG-346 adds the default widget field in the page template descriptor

vuepress/docs/next/tutorials/devops/installation/azure-kubernetes-service/azure-install.md, vuepress/docs/v6.2/tutorials/devops/installation/azure-kubernetes-service/azure-install.md
Nginx deprecated the steps that we have in azure. This updates to the new repos and naming from here:
https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
Which is where the deprecation message points.
=> ENDOC-96 update azure nginx instructions

vuepress/docs/next/docs/reference/entando-apis.md, vuepress/docs/next/tutorials/backend-developers/run-local.md, vuepress/docs/next/tutorials/devops/local-tips-and-tricks.md, vuepress/docs/v6.2/tutorials/backend-developers/run-local.md, vuepress/docs/v6.2/tutorials/devops/local-tips-and-tricks.md
Updated documentation about Swagger UI.
I'm wondering if we should add any line or link about keycloak permissions configuration
=> Endoc 106 update documentation to note swagger ui is enabled by default in quickstart environment as of 6 2 1

vuepress/docs/next/tutorials/backend-developers/build-and-deploy.md, vuepress/docs/next/tutorials/ecr/tutorials/create-ecr-bundle-from-git.md, vuepress/docs/v6.2/tutorials/backend-developers/build-and-deploy.md, vuepress/docs/v6.2/tutorials/ecr/tutorials/create-ecr-bundle-from-git.md
Init a new repository without content (or without added content) raise an error from Git (sorry in french on my environment).
> error: impossible de pousser des références vers 'github.com:avdev4j/testbug.git'
We should follow the Git  worklow when init a new repo. 
> echo "# testbug" >> README.md
> git init
> git add README.md
> git commit -m "first commit"
> git branch -M main
> git remote add origin git@github.com:avdev4j/testbug.git
> git push -u origin main
Those commands are displayed when you create an empty repository.
=> Add "add" and init "commit" phase in documentation when init a new repository.

vuepress/README.md, vuepress/deploy-staging.sh, vuepress/docs/.vuepress/components/css/main.css, vuepress/docs/.vuepress/plugins/entando-nav-version/enhanceAppFile.js
This will switch our staging site from https://es-entando.github.io/ to https://entando.github.io/entando-docs/.
=> ENDOC-66 Switch staging site

vuepress/docs/next/docs/component-generator/component-gen-tech.md, vuepress/package.json, vuepress/yarn.lock
Bumping up the specific dependencies in package.json (manually) and implicit dependencies via yarn upgrade. Will address one specific dependabot warning but we're also a bit overdue. I did some light testing and everything looks okay, the plugins are working fine.
=> Upgrade vuepress and dependencies

vuepress/docs/.vuepress/config.js, vuepress/docs/.vuepress/styles/index.styl, vuepress/package.json
This enables full text search on the site. It's enabled in staging https://entando.github.io/entando-docs/ and all of the content on the pages is now indexed whereas before it was just page and section titles. Phrase searches also work much better now.
=> ENDOC-19 Add full text search

vuepress/docs/.vuepress/components/EntandoVersionLinks.vue, vuepress/docs/.vuepress/config.js, vuepress/docs/.vuepress/navLinks.js, vuepress/docs/.vuepress/plugins/entando-nav-version/enhanceAppFile.js, vuepress/docs/.vuepress/styles/index.styl, vuepress/docs/.vuepress/theme/layouts/Layout.vue
This moves the navigation from the top nav bar over to the side bar, displays the current version more clearly, and makes it easier to switch versions. It still only links to the root page for each section (docs or tutorials), just like before, but this is closer to what other open source projects do. My hands were tied a bit by Vuepress in terms of styling but open to suggestions on improvements.
This is deployed to my github pages site now https://nshaw.github.io/v6.2/docs/ and here's a screenshot.
=> ENDOC-94 Rework version navigation to improve usability

vuepress/deploy-staging.sh, vuepress/docs/.vuepress/components/EntandoCodeCopy.vue, vuepress/docs/.vuepress/components/SpecialLayout.vue, vuepress/docs/.vuepress/components/css/main.css, vuepress/docs/next/docs/getting-started/README.md, vuepress/docs/v6.3/docs/getting-started/README.md
Two tweaks here: 1) Add the code-copy button to the landing pages. Bit of forked code there since the landing pages don't use the theme so they can't use theme plugins. 2) Replace a couple more usages of wget in favor of curl.
=> Endoc 182 minor edits

vuepress/docs/.vuepress/components/SpecialLayout.vue, vuepress/docs/.vuepress/next.js, vuepress/docs/.vuepress/v63.js, vuepress/docs/next/docs/getting-started/README.md, vuepress/docs/next/docs/reference/local-tips-and-tricks.md, vuepress/docs/next/tutorials/README.md, vuepress/docs/next/tutorials/devops/installation/open-shift/openshift-install.md, vuepress/docs/next/tutorials/micro-frontends/react.md, vuepress/docs/v6.3/docs/getting-started/README.md, vuepress/docs/v6.3/docs/reference/local-tips-and-tricks.md, vuepress/docs/v6.3/tutorials/README.md, vuepress/docs/v6.3/tutorials/devops/installation/open-shift/openshift-install.md, vuepress/docs/v6.3/tutorials/micro-frontends/react.md
@w-caffiero-entando and @ichalagashvili ,
Here's my first take on this. I've added a set of next steps linked from the landing pages and the quickstart getting started guide: https://nshaw.github.io/v6.3/docs/getting-started/#next-steps. It points to the (now moved under docs) Tips document with a new Quickstart Management section which includes a handful of FAQ-style questions new users may have: https://nshaw.github.io/v6.3/docs/reference/local-tips-and-tricks.html#quickstart-management. I've pushed this to my GH Pages site for easier review.
=> Endoc 192 quickstart tips

vuepress/docs/.vuepress/components/EntandoRedirect.vue, vuepress/docs/docs/README.md, vuepress/docs/docs/getting-started/README.md, vuepress/docs/tutorials/README.md
This is visible on  my GH Pages - https://nshaw.github.io/docs/, https://nshaw.github.io/docs/getting-started, and https://nshaw.github.io/tutorials. If you watch closely you'll see a message about the redirect but I think that's preferable to a 404 (even temporary) and a full Vue reload.
=> ENDOC-57 Improve redirects from landing pages so the 404 page doesn't display

vuepress/docs/v6.3/docs/ecr/ecr-bundle-details.md
=> Fix UX fragment code which must use an underscore instead of dash

vuepress/docs/.vuepress/components/SpecialLayout.vue
Remove the login link in the landing page top header since it points to the old login area of entando.com rather than keycloak
=> ENDOC-352 Remove login link from landing page

vuepress/docs/next/docs/getting-started/README.md, vuepress/docs/v6.3.2/docs/getting-started/README.md, vuepress/docs/v6.3.2/docs/releases/README.md
ENDOC-370 No Entando support for Apple's M1 chip noted in Getting Started and the Known Issues section of Release Notes
=> ENDOC-370 no support for M1 installation

vuepress/docs/.vuepress/next.js, vuepress/docs/.vuepress/v632.js, vuepress/docs/next/docs/getting-started/README.md, vuepress/docs/v6.3.2/docs/getting-started/README.md
This is a draft and need to assess links, layout and new text. 
Also, when approved, will be added to next version.
=> ENDOC-314 new links on Getting Started draft

vuepress/docs/next/docs/reference/local-tips-and-tricks.md, vuepress/docs/v6.3.2/docs/reference/local-tips-and-tricks.md, vuepress/docs/v6.3.2/tutorials/devops/installation/open-shift/openshift-install-by-operator-hub.md, vuepress/docs/v6.3.2/tutorials/devops/installation/open-shift/openshift-install.md
nothing added yet, just revisiting current content
=> ENDOC-385 tips-and-tricks sheet needs to be reworked/augmented

vuepress/docs/next/docs/concepts/pda-architecture.md, vuepress/docs/next/tutorials/customize-the-platform/pda-tutorial.md
first pass at one of the docs to rework
=> ENDOC-379 Create documentation for the PDA Plugin

vuepress/docs/next/tutorials/samples/install-standard-demo.md, vuepress/docs/v6.3.2/tutorials/samples/install-standard-demo.md
This commit adds the cache clearing workaround and also reorganizes material to flow better with cleaner presentation.
among other offenses, the previous rev: 
- listed a troubleshooting issue as an installation step
- separated 2 options to achieve the same result into 2 different installation steps, and 
- did not explain how to navigate to the demo page until after the fix for missing content was discussed - cue frustrated fumbling and confusion between similar menu options (my dashboard on the demo page vs dashboard in the app)
i'm not happy with it, but it's an improvement. i'd still love to shoot for one-liners wrt step-by-step tutorials...
=> ENDOC-398 Update the Standard Demo cache workaround to use the easier Reload Configuration option

vuepress/docs/next/docs/concepts/README.md, vuepress/docs/v6.3.2/docs/concepts/README.md
The link doesn't work because a) the sidebar depth isn't high enough to differentiate the cited subsection, or b) the subsection directly follows the list item so the link appears nonfunctional to the user (the view of the page would not shift/scroll upon clicking). Given the proximity of subsection reference and subsection including a link is awkward and unnecessary.
=> ENDOC-404 Broken anchor link in Concepts section for 6.3.2

vuepress/docs/next/docs/compose/app-builder.md, vuepress/docs/next/docs/compose/ecm-overview.md, vuepress/docs/v6.3.2/docs/compose/app-builder.md, vuepress/docs/v6.3.2/docs/compose/ecm-overview.md
ecm overview and app builder landing pages were created quasi-simultaneously; valid cross-reference links could not be included until they were committed to main
=> ENDOC-430 Insert cross-reference links

vuepress/docs/next/tutorials/solution/customer-portal.md, vuepress/docs/next/tutorials/solution/entando-hub.md, vuepress/docs/next/tutorials/solution/install-standard-demo.md, vuepress/docs/next/tutorials/solution/pda-tutorial.md, vuepress/docs/v6.3.2/tutorials/solution/landing-page.md
plus v6.3.2 landing page uncommenting. After review will apply to v6.3.2.
=> ENDOC-443 Auto install Hub sections

vuepress/docs/next/tutorials/getting-started/azure-install.md
In the troubleshooting section at the bottom, there is a list of pods that looks wrong. I've listed the new ones below so you can check that these are the correct ones to use, but the status for each pod may be wrong for the error they are talking about.
=> ENDOC-466 Azure install 7.0 update, first draft

vuepress/docs/next/docs/consume/custom-resources.md, vuepress/docs/next/docs/reference/entando-cli.md, vuepress/docs/next/tutorials/create/mfe/widget-configuration.md, vuepress/docs/next/tutorials/devops/backing-up-and-restoring-your-environment.md, vuepress/docs/next/tutorials/devops/external-id-management.md, vuepress/docs/next/tutorials/devops/invoking-api.md
the check-md errors are from the new EKS install guide which haven't been published yet and don't have these errors.
=> ENDOC-480 update ent 6 or v632 mentions

vuepress/docs/v6.3.2/docs/consume/identity-management.md, vuepress/docs/v6.3.2/tutorials/solution/customer-portal.md, vuepress/docs/v6.3.2/tutorials/solution/pda-tutorial.md
Same check-md error, for corrected error in gke-install.md
The Customer Portal page looks like I made a lot of changes but I just switched the order of sections around. I moved the configuration of CP below the configuration of the Keycloak management. Thought that made more sense since the Keycloak part sets up the management of the CP.
=> ENDOC-485 add client role instruction to v632

vuepress/docs/next/docs/reference/entando-cli.md, vuepress/docs/v7.0/docs/reference/entando-cli.md
extensive page rework to improve flow and formatting
=> ENDOC-492 ent CLI troubleshooting and versioning from Notions

vuepress/docs/v7.0/docs/compose/ecr-overview.md, vuepress/docs/v7.0/docs/reference/databases.md
Editing for grammar, standards, and better structure. Attempting to break-up big paragraphs with minor headers, shorter sentences and lists where possible.
=> ENDOC-496 update databases.md & ecr-overview.md

vuepress/docs/next/tutorials/devops/external-id-management.md, vuepress/docs/v7.0/tutorials/devops/external-id-management.md
first commit is a placeholder pending discussion
=> ENDOC-521 Tutorial correction: Connect to an External Keycloak Instance

vuepress/docs/next/docs/getting-started/ent-bundle.md
@nshaw Lines 89 & 115 included information that I wasn't sure was useful, with "**". Let me know your thoughts.
Also @nshaw & @Lyd1aCla1r3, is line 18, first sentence, kind of weird. It's starting to sound weird to me
=> ENDOC-513 new bundle cli page

vuepress/docs/.vuepress/next.js, vuepress/docs/.vuepress/v632.js, vuepress/docs/.vuepress/v70.js
ironic the branch name has a typo too.
the nav had authentification, instead of authentication as the page is called. Probably my mistake to begin with.
=> ENDOC-typo correct authentication in sidebar nav

vuepress/docs/next/docs/releases/README.md
- current as of 2022-08-22 7PM PST
- WIP
- all bolded terms/phrasing in question
=> ENDOC-551 7.1 release notes

vuepress/docs/v7.1/docs/create/blueprint-features.md, vuepress/docs/v7.1/docs/curate/bundle-component-details.md, vuepress/docs/v7.1/tutorials/create/ms/generate-microservices-and-micro-frontends.md
after the review, will copy over to next version
@nshaw, can you read over blueprint-features.md to check technical info is correct?
=> ENDOC-579B updates for blueprint tutorial & static resources

vuepress/docs/next/docs/getting-started/README.md, vuepress/docs/next/docs/getting-started/concepts-overview.md, vuepress/docs/next/tutorials/create/pb/publish-project-bundle.md, vuepress/docs/v7.1/docs/getting-started/README.md, vuepress/docs/v7.1/docs/getting-started/concepts-overview.md, vuepress/docs/v7.1/tutorials/create/pb/publish-project-bundle.md
=> ENDOC-618 fix architecture page - language + updates

vuepress/docs/next/docs/getting-started/ent-bundle.md, vuepress/docs/v7.1/docs/getting-started/ent-bundle.md
i am absolutely overthinking this. @jyunmitch which do you like better?
=> ENDOC-645 Support native k8s image builds in CI/CD pipelines

vuepress/docs/v7.3/docs/curate/bundle-details.md, vuepress/docs/v7.3/docs/getting-started/ent-bundle.md
just copying previous update to v7.3. Luca C said the bundle name validation is only for 7.3.
=> ENDOC-741 copy changes to v7.3

vuepress/docs/v7.3/docs/curate/bundle-details.md
This pull request addresses the discrepancy in the type definition for the resources field in the microservice model. The current implementation uses an array type, which causes issues during deployment. The correct type should be a plain JSON object.
The ent CLI does not perform any validation on the microservice model during `pack` execution, leading to potential errors during deployment.
```json
{
"name": "testms",
"stack": "custom",
"dbms": "postgresql",
"healthCheckPath": "/api/health",
"commands": {
"build": "...",
"run": "...",
"pack": "..."
},
"version": "0.0.5",
"resources": [  // valid, no errors during pack phase
{"cpu": "100m"},
{"memory": "128M"}
]
}
```
```json
{
"name": "testms",
"stack": "custom",
"dbms": "postgresql",
"healthCheckPath": "/api/health",
"commands": { …
```
=> Fix 'resources' type description
